[2023-05-08T22:36:58.123+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: veryfi_extract_total.create_table scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-05-08T22:36:58.141+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: veryfi_extract_total.create_table scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-05-08T22:36:58.142+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-08T22:36:58.156+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-08 00:00:00+00:00
[2023-05-08T22:36:58.162+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2023-05-08T22:36:58.167+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'veryfi_extract_total', 'create_table', 'scheduled__2023-05-08T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ml_response_dag.py', '--cfg-path', '/tmp/tmpvd_8dr9t']
[2023-05-08T22:36:58.168+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_table
[2023-05-08T22:36:58.306+0000] {task_command.py:410} INFO - Running <TaskInstance: veryfi_extract_total.create_table scheduled__2023-05-08T00:00:00+00:00 [running]> on host 916d3785c91c
[2023-05-08T22:36:58.638+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='veryfi_extract_total' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-08T00:00:00+00:00'
[2023-05-08T22:36:58.643+0000] {sql.py:262} INFO - Executing: CREATE TABLE IF NOT EXISTS parsed_total (id SERIAL PRIMARY KEY, total FLOAT);
[2023-05-08T22:36:58.708+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-05-08T22:36:58.745+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=veryfi_extract_total, task_id=create_table, execution_date=20230508T000000, start_date=20230508T223658, end_date=20230508T223658
[2023-05-08T22:36:58.824+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task create_table (The conn_id `postgres` isn't defined; 63)
[2023-05-08T22:36:58.871+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T22:36:59.009+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
